# docker-compose wind-api

services:
  app:
    build: .
    image: wind-api:${APP_VERSION}
    environment:
      - APP_VERSION=${APP_VERSION}
    ports:
      - "3000:3000"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    networks:
      - wind-app-network

  postgres:
    image: postgres:18.1
    container_name: wind-api-postgres
    environment:
      POSTGRES_PASSWORD: 123123
      POSTGRES_USER: postgres
      POSTGRES_DB: wind_db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user"]  # ✅ 检查 PostgreSQL 是否 ready
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres_data:/var/lib/postgresql
    networks:
      - wind-app-network

  redis:
    image: redis:8.4.0
    container_name: wind-api-redis
    ports:
      - "6379:6379"
    volumes:
      - ./data/redis:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]  # ✅ 发 PING，期待 PONG
      interval: 1s
      timeout: 3s
      retries: 10
    networks:
      - wind-app-network

  rabbitmq:
    image: rabbitmq:4.2
    container_name: wind-api-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - ./data/rabbitmq:/var/lib/rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: 123123
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]  # ✅ 关键！添加这一行
      interval: 10s
      timeout: 5s
      retries: 6
    networks:
      - wind-app-network

networks:
  wind-app-network:
    driver: bridge

volumes:
  wind_app_data:
